//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Runtime.InteropServices;
using System.Reflection;

[assembly: AssemblyTitle("Scripts")]
[assembly: AssemblyProduct("Album Art Downloader")]

[assembly: NeutralResourcesLanguageAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: System.Windows.ThemeInfo(System.Windows.ResourceDictionaryLocation.None, System.Windows.ResourceDictionaryLocation.SourceAssembly)]
[assembly: AssemblyVersion("0.1.0.0")]